config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'pins#index'
  resources :pins
  resources :categories, only: [:index, :show]

  patch 'pins/:id/add_category', to: 'pins#add_category'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :pin_categories
  has_many :pins, through: :pin_categories
  has_many :users, through: :pins
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  validates_presence_of :title, :url, :text, :user_id
  has_many :pin_categories
  has_many :categories, through: :pin_categories
  belongs_to :user
  before_create :normalize_url!
  accepts_nested_attributes_for :categories, reject_if: proc { |attributes| attributes['name'].blank? }

  has_attached_file :image, styles: { medium: "300x300>"}, default_url: "http://placebear.com/300/300" 
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  def self.most_popular_category
    popular = self.group(:category_id).count

    popular.each do |key, value| 
       id = key if value == popular.values.max
    end

    if id == nil
       "unkown"
    else
      category = Category.find(@id)
      category.name
    end
  end

<<<<<<< HEAD
  def self.search(title)
     where(title: title)
  end

  def category_name=(name)
      category = Category.find_or_create_by(:name => name)
      self.categories << category unless self.categories.include? category
=======
  def categories_attributes=(category_attributes)
    category_attributes.values.each do |category_attribute|
      if category_attribute["name"] != ""
        category = Category.find_or_create_by(category_attribute)
        self.categories << category unless self.categories.include? category
      end
    end
>>>>>>> JS
  end

 def normalize_url!
   self.url = url.start_with?("http") ? url : "http://" + "#{url}"
end

end

app/models/pin_category.rb
class PinCategory < ActiveRecord::Base 
  belongs_to :pin
  belongs_to :category 
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]   
  has_many :pins 
  has_many :categories, through: :pins
  has_one :profile    

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end      
  end         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:show, :show_by_name]

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end

  def logged_in?
    !current_user.nil? && !current_user.id.nil?
  end
  helper_method :logged_in?
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @categories}
    end
    @pins = current_user.pins
  end

  def show
    @category = Category.find(params[:id])
     respond_to do |format|
      format.html {render :show}
      format.json {render json: @category}
    end   
  end

  def create
    @category = Category.create(pin_params)
    # @pin = @pin.categories.build(name: params[:name])
    render json: @pin, status: 201
  end


end


private

  def pin_params
    params.require(:pin).permit(:title, :url, :text, :user_id, :image, category_ids:[], categories_attributes: [:name] )
  end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  
  def index
    @pins = current_user.pins

    respond_to do |format|
      format.html {render :index}
      format.json {render json: @pins}
    end

    # @pins = Pin.search("Girl Develop It")
  end

  def new
    @pin = Pin.new
  end
  
  def show
    @pin = Pin.find(params[:id])
     respond_to do |format|
      format.html {render :show}
      format.json {render json: @pin}
    end   
  end

  def create
    @pin = Pin.new(pin_params)
    @pin.user_id = current_user.id

    if @pin.valid?
      @pin.save
      redirect_to pin_path(@pin)
      # render json: @pin, status: 201
    else
      @errors = @pin.errors
      render :new
    end
  end

  def edit
    @pin = Pin.find(params[:id])
  end

  def update
    @pin = Pin.find(params[:id])
    
    if @pin.update(pin_params)
      redirect_to @pin
    else
      @errors = @pin.errors
      render :edit
    end
  end

  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy!
    redirect_to pins_path
  end

  def show_by_name
    @pin = Pin.find_by_slug(params[:slug])
    render :show
  end

  def add_category
    @pin = Pin.find(params[:id])
    
    @pin.update(pin_params)
      respond_to do |format|
        format.html {render :show}
        format.json {render json: @pin, status: 201}
    end
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :url, :text, :user_id, :image, category_ids:[], categories_attributes: [:name] )
  end
  
end

app/controllers/profiles_controller.rb
# class ProfilesController < ApplicationController
#   # def create
#   #   ingrediebt_attributes=
#   # end

#   def show
#     @user = current_user

#     if @user.profile = nil
#       redirect_to new profile
#     else

#   end

#   def edit  

#   end

#   def update
    
#   end

#   private

#   def profile_params
#     params.require(:user).permit(preferences_attributes: [:name])
#   end
# end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
 
    def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pincategories_helper.rb
module PincategoriesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
    # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/categories/index.html.erb
<div class="pins">
  <h4>
    <%=link_to "= Display All Pins =", pins_path %>
  </h4>
  <h1 style="text-decoration: underline;">CATEGORIES:</h1>
    <ul class="block">
      <% @categories.each do |category| %>
      <% if category.name == "" %>
        <h2><%= "unassigned" %></h2>
      <% else %>
        <h2><%= "#{category.name.pluralize}" %></h2>
      <% end %>
      
        <% category.pins.each_slice(3) do |row| %> 
          <div class="row">
            <% row.each do |pin| %>      
                <div class="pin-container col-md-4">
                  <div class="pin">
                    <div class="pin-header row">
                      <div>
                          <% if pin.image %>
                            <img src="<%= pin.image.url(:medium) %>">
                          <% end %>
                        </div>
                      </div>
                    <div>
                  <h4>
                    <%=link_to "#{pin.title}", pin_path(pin)%>
                  </h4>
                    <%= link_to "#{pin.url}", pin.url, html_options = {target: "_blank", class: "url"} %><br>
                  </div>
                <hr/>
              <h5><%= "#{pin.text}" %></h5>
            </div>
          </div>
        <% end %>
      </div>
    <%end %>
  <% end %>
  </ul>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Add a Pin!",new_pin_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to("Sign out", destroy_user_session_path, :method => 'delete') %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>We Code Too!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Amatic+SC:700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Walter+Turncoat' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

<div class="container">
  <div id="notice">
  <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
  <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
  <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>  
  </div>


  <%= yield %>

</div>
</body>
</html>

app/views/pins/_form.html.erb
<div class="row">

  <% if !@errors.nil? %>
      <div class="error">
        <label><%= pluralize(@errors.count, "error") %> prohibited this pin from
        being saved:</label>
      <ul>
        <% @errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>  
    </div>  
  <% end %>

  <%= form_for(@pin, multipart: true) do |f| %>

    <div class="form-group">
      <label for="pin_category_id" class="col-sm-2 control-label">Category</label>
      <div class="col-sm-10 ">
        <div class="scroll form-control">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, prompt: 'or select categories'%>
        </div><br>

      <%= f.fields_for :categories, @pin.categories.build do |categories_fields| %>
        <%= categories_fields.text_field :name, placeholder: "Or Create a New Category!", class: "form-control" %>
      <% end %> 
      </div>
    </div>

    <div class="form-group">
      <label for="pin_title" class="col-sm-2 control-label">Title</label>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <label for="pin_url" class="col-sm-2 control-label">Url</label>
      <div class="col-sm-10">
        <%= f.text_field :url, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <label for="pin_text" class="col-sm-2 control-label">Description</label>
      <div class="col-sm-10">
        <%= f.text_area :text, class: "form-control" %>
      </div>
    </div>  

    <div class="form-group">
      <label for="pin_image" class="col-sm-2 control-label">Image</label>
      <div class="col-sm-10">
      <%= f.file_field :image, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-2">
      </div>
      <div class="col-sm-10">
        <%= f.button(options = {class: "btn btn-default form-control"}) %>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/edit.html.erb
<div class="row">
  <h1>Edit Pin!</h1>
</div>

<%= render 'form' %>

app/views/pins/index.html.erb
<div>
  <h1 class="title">WE CODE TOO!</h1><h3>A Collection of Diversity-Friendly Tech Resources!</h3>
  <p class="current_user">You are logged in as: <%= current_user.email %></p><br>  
</div>
<hr/>


<div class="pins">
  <% if @pins.empty? %>
  <h1 style="color:brown;">You have no pins! <br> <%= link_to "Add",new_pin_path %> some to display here!</h1>
  <% else %>
  <h4>
    <%=link_to "= Display Pins by Category =", categories_path %>
  </h4>
  <% @pins.each_slice(3) do |row| %>
    <div class="row">
      <% row.each do |pin| %>      
        <div class="pin-container col-md-4">
          <div class="pin">
            <div class="pin-header row">
              <div>
                  <% if pin.image %>
                    <img src="<%= pin.image.url(:medium) %>">
                    <% end %>
                  </div>
                </div>

            <div >
              <h4>
                <%=link_to "#{pin.title}", pin_path(pin)%>
              </h4>
                <%= link_to "#{pin.url}", pin.url, html_options = {target: "_blank", class: "url"} %>
            </div>
            <hr/>
            <button class="js-more btn btn-default form-control" data-id="<%= pin.id %>">More Info</button>
            <div id="pin-<%= pin.id %>"><%= truncate(pin.text, length:0) %></div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <% end %>
</div>
<script type="text/javascript" charset="utf-8">
$(function() {
  $(".js-more").on("click", function() {
    var id = $(this).data("id");
    $.get("/pins/" + id + ".json", function(data) {
      var pin = data["pin"];
      var pinCategories = []
        if(pin["categories"][0] == undefined ){
          var pinCategory = "Category: Unassigned";
        } else if (pin["categories"].length > 1){
          for(i=0; i < pin["categories"].length; i++){
             
            pinCategories.push(" " + pin["categories"][i]["name"]); 

            var pinCategory = "<div>Categories: " + pinCategories + "</div>";
          } 
        } else {
          var pinCategory = "<div>Category: " + pin["categories"][0]["name"] + "</div>";
        }


      var descriptionText = "<br><p><strong>" + pin["text"] + "</strong></p>" + pinCategory;
      $("#pin-" + id).html(descriptionText);
    });
  });
});
</script>
<hr/>

app/views/pins/new.html.erb
<div class="row">
  <h1>New Pin!</h1>
</div>

<%= render 'form' %>

app/views/pins/show.html.erb
<div class="show">
  <div class="header">
    <h1 class="pinTitle">
      <%= "#{@pin.title}" %>
    </h1>
  </div>
        <%= link_to "Edit Pin", edit_pin_path(@pin) %><br>
        <%= link_to "Delete Pin", pin_path(@pin), :confirm => "Are you sure?", :method => :delete, :prompt => "Are you sure?" %><br>
        <a href="#" class="js-next" data-id="<%=@pin.id%>">Next Pin</a>
        <hr>

  <div class="show-pin">
    <img class="pinImage" src="<%= @pin.image.url(:medium) %>" ><br><br>
    <p class="pinText"><%= "#{@pin.text.upcase}" %></p>

    <hr/>
    <p>
      <b class="pinTitle">Visit: <%= "#{@pin.title}" %> at: </b>
        <%= link_to "#{@pin.url}", @pin.url, html_options = {target: "_blank", class: "url pinUrl"} %><br><br>
    </p>

    <% @pin.categories.each do |category| %> 
        <li class="pinCategory"><%= "#{category.name.upcase}" %></li>
    <% end %>

    <br><br>

    <%= form_for @pin, url: {action: "add_category"} do |f| %>
      <div class="col-sm-6">
        <%= f.fields_for :categories, @pin.categories.build do |categories_fields| %>
          <%= categories_fields.text_field :name, class: "form-control" %>
        <% end %> 
       </div>
      <div class="col-sm-6">
        <%= f.submit "Add Categories",(options = {class: "btn btn-default form-control"}) %>
      </div>     
    <% end %>

<script type="text/javascript" charset="utf-8">
  $(function () {
    $('form').submit(function(event) {
    alert(data);
      event.preventDefault();
  
      var values = $(this).serialize();
 
      var posting = $.post('/pins', values);
 
      posting.done(function(data) {
        var pin = data["pin"];
        $(".pinCategory").append("<li>" + pin["categories"]["name"] + "</li>");
      });
    });
  });
</script>

  <script type="text/javascript" charset="utf-8">
  $(function () {
    $(".js-next").on("click", function() {
      var nextId = parseInt($(".js-next").attr("data-id")) + 1;
      $.get("/pins/" + nextId + ".json", function(data) {
        var pin = data["pin"];
        
        if(pin["categories"][0] == undefined ){
          $(".pinCategory").text("Category Unassigned");
        } else if (pin["categories"].length > 1){
          for(i=0; i < pin["categories"].length; i++){
            $(".pinCategory").append("<li>" + pin["categories"][i]["name"] + "</li>"); 
          } 
        } else {
          $(".pinCategory").text(pin["categories"][0]["name"]);
        }

        $(".pinTitle").text(pin["title"]);
        $(".pinUrl").text(pin["url"]);
        $(".pinText").text(pin["text"]);
        $(".pinImage").attr("src",pin["image"]);
        $(".js-next").attr("data-id", pin["id"]);
      });
    });
  });
  </script>  
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= form_for @profile do |f| %>
        <h1>Profile Preferences:</h1><br><br><br>
        <ul>
          <%= f.fields_for :preferences do |preferences_form| %>

            <div class="form-group">
              <label for="pin_title" class="col-sm-2 control-label">Name</label>
              <div class="col-sm-10">
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-2">
              </div>
              <div class="col-sm-10">
                <%= f.button "Save", (options = {class: "btn btn-default form-control"}) %>
            </div>
          <% end %>
        </ul>
      <% end %>
    </section>
  </aside>
</div>

app/views/profiles/show.html.erb
<h1> Your Profile: </h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
  <%= link_to "Edit Profile", "#" %>